# Generated by Django 4.0.6 on 2022-07-21 15:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_category_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=cloudinary.models.CloudinaryField(default='image', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
